### ISSUE TITLE
Missing include

### ISSUE THREAD

**Issue by loostrum** [nlesc-recruit/PowerSensor3#72]
For some users, an include seems to be missing. TBD for which OS / compiler versions this is happening.
See https://gitlab.com/astron-misc/libpowersensor/-/merge_requests/7#note_1048943937

**Comment by csbnw** [comment]
This occurs with Fedora 36 and GCC 12.1.1.

**Comment by loostrum** [comment]
I don't see this error with GCC 10/11, but I can reproduce it with GCC 12. I'll add the missing array include.
